api/src/portal/urls.py
from django.urls import path
from . import views

app_name = 'portal'

urlpatterns = [
     path('bus_list/', views.bus_list, name='bus_list'),
     path('bus_delete/<int:id>/',views.bus_delete, name='bus_delete'),
     path('bus_update/<int:id>/', views.bus_update, name='bus_update'),
     path('bus_create/',views.bus_create , name='bus_create' ),

     path('route_list/', views.route_list, name='route_list'),
     path('route_delete/<int:id>/',views.route_delete, name='route_delete'),
     path('route_update/<int:id>/',views.route_update, name='route_update'),
     path('route_create/',views.route_create , name='route_create'),

     path('schedule_create/',views.schedule_create , name='schedule_create'),
     path('schedule_list/',views.schedule_list , name='schedule_list'),
     path('schedule_delete/<int:id>/',views.schedule_delete , name='schedule_delete'),

     path('schedules/',views.schedule_search , name='schedule_search'),
     path('select_seat/',views.seat_seat ,name ='select_seat'),
]

api/urls.py
"""api URL Configuration."""

from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Bus Reservation",
      default_version='v1',
      description="drf rest api",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

# handler404 = "handler404"

urlpatterns = [
   path('admin/', admin.site.urls),
   path('api/v1/auth/', include('api.src.authentication.urls')),
   path('api/v1/tickets/', include('api.src.tickets.urls')),
   path('api/v1/portal/', include('api.src.portal.urls')),
   path('', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
   path('__debug__/', include('debug_toolbar.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <title>Bus Reservation</title>
</head>
<body>
    <div class="container">
      {%block nav%}{%endblock%}
      <div class="row">
        <div class="col-6">
          {%block content%}{%endblock%}
        </div>
        <div class="col-6">
          {%block scontent%}{%endblock%}
        </div>
      </div>
    </div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</body>
</html>

templates/bus_create.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{% load crispy_forms_tags %}
{%block content%}

<div class="card" >
    <div class="card-body">
        <form method="post">
             {% csrf_token %}
        <fieldset class="form-group">
            {{busform|crispy }}
            <!-- {{busform}} -->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">CREATE NEW BUS</button>
            <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:bus_list' %}" type="submit">GO BACK TO LIST</button>
         </div>
        </form>
    </div>
</div>
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional information</h5>
    <p class="card-text"> A bus can only contain a <b>minimum of 14 seats</b> and a <b>maxmum of 67 seats</b> </p>
    
  </div>
</div>


{%endblock%}

templates/bus_list.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{%block content%}
      {%for bus in buses%}

      <div class="card">
         <div class="card-body">
           <h5 class="card-title"><b>Bus Name:</b> {{bus.bus_name}}</h5>
           <p class="card-text"> <b>No_of_seats:</b> {{bus.no_of_seat}} </p>
           <button class="btn btn-info" onclick=location.href="{% url 'portal:bus_update' bus.id %}"  >update</button>
           <button class="btn btn-danger" onclick=location.href="{% url 'portal:bus_delete' bus.id %}"  >Delete</button>
         </div>
      </div>

      {%endfor%}
  
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional links</h5>
    <p class="card-text"> Click the button bellow to create new bus ... </p>
    <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:bus_create' %}" type="submit">CREATE BUS</button>
  </div>
</div>


{%endblock%}

templates/bus_update.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{% load crispy_forms_tags %}
{%block content%}

<div class="card" >
    <div class="card-body">
        <form method="post">
             {% csrf_token %}
        <fieldset class="form-group">
            {{busform|crispy }}
            <!-- {{busform}} -->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">UPDATE</button>
            <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:bus_list' %}" type="submit">CANCEL</button>
         </div>
        </form>
    </div>
</div>
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional information</h5>
    <p class="card-text"> A bus can only contain a <b>minimum of 14 seats</b> and a <b>maxmum of 67 seats</b> </p>
    
  </div>
</div>


{%endblock%}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">{B.R.S}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'portal:bus_list' %}">Buses</a>
        </li>

        <li class="nav-item active">
           <a class="nav-link" href="{% url 'portal:route_list' %}">Routes</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'portal:schedule_list' %}">Shedules</a>
        </li>
      </ul>
    </div>
  </nav>

templates/route_create.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{% load crispy_forms_tags %}
{%block content%}

<div class="card" >
    <div class="card-body">
        <form method="post">
             {% csrf_token %}
        <fieldset class="form-group">
            {{routeform|crispy }}
            <!-- {{routeform}} -->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">CREATE NEW ROUTE</button>
            <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:route_list' %}" type="submit">GO BACK TO LIST</button>
         </div>
        </form>
    </div>
</div>
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional information</h5>
    <p class="card-text"> A route name should start with a alphabet character</p>
  </div>
</div>


{%endblock%}

templates/route_list.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{%block content%}
      {%for route in routes%}

      <div class="card">
         <div class="card-body">
           <h5 class="card-title"><b>From:</b> {{route.from_destination}} <b>To:</b> {{route.to_destination}}</h5>
           <p class="card-text"> <b>N.B:</b><i> Route stop overs coming soon...</i> </p>
           <button class="btn btn-info" onclick=location.href="{% url 'portal:route_update' route.id %}"  >update</button>
           <button class="btn btn-danger" onclick=location.href="{% url 'portal:route_delete' route.id %}"  >Delete</button>
         </div>
      </div>

      {%endfor%}
  
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional links</h5>
    <p class="card-text"> Click the button bellow to create new route....</p>
    <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:route_create' %}" type="submit">CREATE ROUTE</button>
  </div>
</div>


{%endblock%}

templates/route_update.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{% load crispy_forms_tags %}
{%block content%}

<div class="card" >
    <div class="card-body">
        <form method="post">
             {% csrf_token %}
        <fieldset class="form-group">
            {{routeform|crispy }}
            <!-- {{routeform}} -->
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">update</button>
            <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:route_list' %}" type="submit">cancel</button>
         </div>
        </form>
    </div>
</div>
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional information</h5>
    <p class="card-text"> A route name should start with a alphabet character</p>
  </div>
</div>


{%endblock%}

templates/schedule_create.html
{% extends "base.html"%}
{%block nav%}
{%include "navbar.html"%}
{%endblock%}
{% load crispy_forms_tags %}
{%block content%}

<div class="card" >
    <div class="card-body">
        <form method="post">
             {% csrf_token %}
        <fieldset class="form-group">
            {{scheduleform|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">CREATE NEW SCHEDULE</button>
            <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:schedule_list' %}" type="submit">GO BACK TO LIST</button>
         </div>
        </form>
    </div>
</div>
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional information</h5>
    <p class="card-text"> A bus can only contain a <b>minimum of 14 seats</b> and a <b>maxmum of 67 seats</b> </p>
  </div>
</div>


{%endblock%}

templates/schedule_list.html
{% extends "base.html"%}
{%block content%}
      {%for schedule in schedules%}

      <div class="card">
         <div class="card-body">
           <h5 class="card-title"><b>From:</b> {{schedule.departure_time}}</h5>
           <p class="card-text"> <b>To:</b> {{schedule.arrival_time}} </p>
           <button class="btn btn-danger" onclick=location.href="{% url 'portal:schedule_delete' schedule.id %}">Delete</button>
         </div>
      </div>

      {%endfor%}
  
{%endblock%}

{%block scontent%}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Aditional links</h5>
    <p class="card-text"> Click the button bellow to access new schedule form </p>
    <button class="btn btn-outline-info" onclick=location.href="{% url 'portal:schedule_create' %}" type="submit">CREATE SCHEDULE</button>
  </div>
</div>


{%endblock%}

templates/search_schedule.html
{% extends "base.html"%}
{% load crispy_forms_tags %}
{%block content%}
  
      {%for schedule in schedules%}
      <div class="card">
         <div class="card-body">
           <h5 class="card-title"><b>Route:</b> {{schedule.route}}</h5>
           <p class="card-text"> <b>bus:</b> {{schedule.bus}} </p>
           <p class="card-text"> <b>Date:</b> {{schedule.date_of_travel}} </p>
           <p class="card-text"> <b>Departure Time:</b> {{schedule.arrival_time}} </p>
           <p class="card-text"> <b>Arrival_Time:</b> {{schedule.arrival_time}} </p>
           <button class="btn btn-info" onclick=location.href="{% url 'portal:select_seat' %}">Next Select Seat</button>
         </div>
         
      </div>

      {%endfor%}
  
{%endblock%}

{%block scontent%}
<div class="card" >
    <div class="card-body">
        <form method="get"> 
          {{myfilter.form|crispy}}
          <input type="submit" value="search"/>
        </form>
    </div>
</div> 


{%endblock%}

templates/select_seat.html
{% extends "base.html"%}

{%block content%}

    <h3>...comming soon...</h3>

{%endblock%}